channels:
  - conda-forge
dependencies:
  # binderhub default values
  - python=3.7
  - ipywidgets==7.5.1
  - jupyterlab==1.2.6
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - nbresuse==0.3.3
  - notebook==6.0.3
  - nteract_on_jupyter==2.1.3
  # Python Deps -> python is already included in the default image
  - numpy==1.18.5
  - matplotlib==3.2.2
  - seaborn==0.10.1
  - pandas==1.0.5
  # R Deps
  # - r-base==4.0.2
  # - r-tidyverse==1.2.1
  # Julia Deps
  # - julia==1.1.1
